# Generated by Django 2.0.5 on 2019-02-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_selfbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carid', models.CharField(max_length=10)),
                ('Userid', models.CharField(max_length=10)),
                ('bookingdate', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('Days', models.IntegerField(default=0)),
                ('ActualPrice', models.IntegerField(default=0)),
                ('ServiceRating', models.IntegerField(default=10)),
                ('ServiceDesc', models.CharField(default='', max_length=50)),
                ('CarRating', models.IntegerField(default=10)),
                ('CarDesc', models.CharField(default='', max_length=50)),
                ('Damage', models.CharField(default='', max_length=50)),
                ('DamageCost', models.IntegerField(default=0)),
            ],
        ),
    ]
