# Generated by Django 2.0.5 on 2019-02-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_selfbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfbooking',
            name='ti',
            field=models.IntegerField(default=0),
        ),
    ]
