# Generated by Django 2.0.5 on 2019-03-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_selfbooking_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringcar',
            name='Driverid',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='hiringcar',
            name='Userid',
            field=models.CharField(max_length=12),
        ),
    ]
