# Generated by Django 2.0.5 on 2019-03-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_hirecancelrepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfcancelrepo',
            old_name='Driverid',
            new_name='Carid',
        ),
    ]
