# Generated by Django 2.0.5 on 2019-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDriveCar',
            fields=[
                ('CarRegistration', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CarCompany', models.CharField(max_length=30)),
                ('CarName', models.CharField(max_length=30)),
                ('CarCapacity', models.IntegerField()),
                ('Cartype', models.CharField(max_length=10)),
                ('carpreowned', models.BinaryField()),
                ('CarBoughtDate', models.DateTimeField()),
                ('CarDescription', models.CharField(max_length=300)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('CarCost', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('ExpectedPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveMaintanence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarReg', models.CharField(max_length=10)),
                ('Date', models.DateTimeField()),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selfdrivemaintanence',
            unique_together={('CarReg', 'Date')},
        ),
    ]
