# Generated by Django 2.0.5 on 2019-02-25 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driverid', models.CharField(max_length=10)),
                ('Userid', models.CharField(max_length=10)),
                ('Pickup', models.CharField(max_length=300)),
                ('Time', models.IntegerField(default=0)),
                ('Date', models.DateTimeField()),
                ('ExpectedPrice', models.IntegerField(default=0)),
                ('ActualPrice', models.IntegerField(default=0)),
                ('DriverRating', models.IntegerField(default=10)),
                ('DriverDesc', models.CharField(default='', max_length=50)),
                ('ServiceRating', models.IntegerField(default=10)),
                ('ServiceDesc', models.CharField(default='', max_length=50)),
                ('Damage', models.CharField(default='', max_length=50)),
                ('DamageCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelfBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carid', models.CharField(max_length=10)),
                ('Userid', models.CharField(max_length=10)),
                ('Date', models.DateTimeField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Days', models.IntegerField(default=0)),
                ('ActualPrice', models.IntegerField(default=0)),
                ('ServiceRating', models.IntegerField(default=10)),
                ('ServiceDesc', models.CharField(default='', max_length=50)),
                ('CarRating', models.IntegerField(default=10)),
                ('CarDesc', models.CharField(default='', max_length=50)),
                ('Damage', models.CharField(default='', max_length=50)),
                ('DamageCost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userdb',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('pincode', models.CharField(default='', max_length=7)),
                ('gender', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selfbooking',
            unique_together={('Carid', 'Userid', 'Date')},
        ),
        migrations.AlterUniqueTogether(
            name='hiringcar',
            unique_together={('Driverid', 'Userid', 'Date')},
        ),
    ]
