# Generated by Django 2.0.5 on 2019-02-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_auto_20190225_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiredcar',
            name='CarBoughtDate',
        ),
        migrations.RemoveField(
            model_name='hiredcar',
            name='carpreowned',
        ),
    ]
