# Generated by Django 2.0.5 on 2019-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_auto_20190226_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredcar',
            name='CarCompany',
            field=models.CharField(default='maruti', max_length=30),
        ),
        migrations.AlterField(
            model_name='hiredcar',
            name='CarDescription',
            field=models.CharField(default='', max_length=300),
        ),
    ]
