# Generated by Django 2.0.5 on 2019-03-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_auto_20190226_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysalary',
            unique_together=set(),
        ),
    ]
