# Generated by Django 2.0.5 on 2019-03-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_auto_20190303_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='month',
            field=models.CharField(default='january', max_length=15),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
