# Generated by Django 2.0.5 on 2019-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_auto_20190303_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdb',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
