# Generated by Django 2.0.5 on 2019-03-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0008_driverdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredcar',
            name='availability',
            field=models.CharField(default='yes', max_length=4),
        ),
    ]
