# Generated by Django 2.0.5 on 2019-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintanenceccost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.CharField(default='', max_length=15)),
                ('cost', models.IntegerField(default=0)),
                ('type', models.CharField(default='self', max_length=5)),
            ],
        ),
    ]
