# Generated by Django 2.0.5 on 2019-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_maintanenceccost'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanenceccost',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
