# Generated by Django 2.0.5 on 2019-03-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_maintanenceccost_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintanenceccost',
            new_name='Maintanencecost',
        ),
    ]
